# -*- coding: utf-8 -*-
"""Plant Disease identification.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VH-g1uI12xjL2S2msrE0LDQwAGCRZJf-
"""

class PlantDiseaseIdentification:
    def __init__(self):
        self.disease_data = {
            "Leaf Spot": {"symptoms": ["dark spots on leaves", "yellowing of leaves"], "image": "leaf_spot.jpg"},
            "Powdery Mildew": {"symptoms": ["white powdery substance on leaves"], "image": "powdery_mildew.jpg"},
            "Bacterial Blight": {"symptoms": ["water-soaked lesions", "wilting of leaves"], "image": "bacterial_blight.jpg"},
            "Rust": {"symptoms": ["orange or reddish-brown spots on leaves"], "image": "rust.jpg"},
            "Downy Mildew": {"symptoms": ["fuzzy, white or grayish spots on leaves"], "image": "downy_mildew.jpg"},
            "Anthracnose": {"symptoms": ["dark, sunken lesions on leaves and stems"], "image": "anthracnose.jpg"}
            # Add more diseases as needed
        }

    def identify_disease(self, symptoms, plant_type):
        possible_diseases = [disease for disease, data in self.disease_data.items() if all(symptom in symptoms for symptom in data["symptoms"])]

        if plant_type.lower() == "fruit":
            # Filter diseases that commonly affect fruit plants
            possible_diseases = [disease for disease in possible_diseases if disease in ["Leaf Spot", "Bacterial Blight", "Anthracnose"]]

        return possible_diseases if possible_diseases else ["Unknown disease"]

    def display_image(self, disease):
        if disease != ["Unknown disease"]:
            for d in disease:
                print(f"Image for {d}: {self.disease_data[d]['image']}")
        else:
            print("Image not available for unknown disease.")

    def run_expert_system(self):
        print("Plant Disease Identification Expert System")

        symptoms = input("Enter the symptoms observed (comma-separated): ").split(',')
        plant_type = input("Enter the type of plant (e.g., fruit, vegetable): ")

        possible_diseases = self.identify_disease(symptoms, plant_type)

        print("\nPossible Diseases:")
        for disease in possible_diseases:
            print(f"- {disease}")

        self.display_image(possible_diseases)

if __name__ == "__main__":
    plant_disease_system = PlantDiseaseIdentification()
    plant_disease_system.run_expert_system()